# Generated by Django 5.2.5 on 2025-10-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="function",
            name="best_case_time_formula",
        ),
        migrations.RemoveField(
            model_name="function",
            name="median_case_time_formula",
        ),
        migrations.RemoveField(
            model_name="function",
            name="worst_case_time_formula",
        ),
        migrations.AddField(
            model_name="function",
            name="execution_time_formula",
            field=models.CharField(default="0", max_length=255),
            preserve_default=False,
        ),
    ]
