# Generated by Django 5.2.5 on 2025-10-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_remove_function_best_case_time_formula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='function',
            unique_together={('device', 'name')},
        ),
    ]
