# Generated by Django 5.2.5 on 2025-10-28 17:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('device', '0002_remove_function_best_case_time_formula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StepGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('steps', models.ManyToManyField(to='process.basestep')),
            ],
        ),
        migrations.CreateModel(
            name='StepIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.basestep')),
            ],
        ),
        migrations.CreateModel(
            name='SwimLane',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process')),
            ],
        ),
        migrations.AddField(
            model_name='basestep',
            name='swim_lane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.swimlane'),
        ),
        migrations.CreateModel(
            name='SwimLaneIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('swim_lane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.swimlane')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionStep',
            fields=[
                ('basestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='process.basestep')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.function')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('process.basestep',),
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('basestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='process.basestep')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process')),
                ('swim_lanes_constraint', models.ManyToManyField(to='process.swimlane')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('process.basestep',),
        ),
    ]
