# Generated by Django 5.2.5 on 2025-10-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='swim_lanes_constraint',
            field=models.ManyToManyField(blank=True, to='process.swimlane'),
        ),
    ]
