# Generated by Django 5.2.5 on 2025-10-31 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('device', '0002_initial'),
        ('process', '0001_initial'),
        ('timed_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('basetimeditem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timed_item.basetimeditem')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('timed_item.basetimeditem',),
        ),
        migrations.AddField(
            model_name='basestep',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='StepIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.basestep')),
            ],
        ),
        migrations.CreateModel(
            name='StepParallelization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('steps', models.ManyToManyField(to='process.basestep')),
            ],
        ),
        migrations.CreateModel(
            name='Swimlane',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process')),
            ],
        ),
        migrations.AddField(
            model_name='basestep',
            name='swimlane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.swimlane'),
        ),
        migrations.CreateModel(
            name='SwimlaneIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('swimlane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.swimlane')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionStep',
            fields=[
                ('basestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='process.basestep')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.function')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('process.basestep',),
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('basestep_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='process.basestep')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process')),
                ('swimlanes_constraint', models.ManyToManyField(blank=True, to='process.swimlane')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('process.basestep',),
        ),
    ]
