# Generated by Django 5.2.5 on 2025-10-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_alter_processstep_swim_lanes_constraint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StepGroup',
            new_name='StepSynchronization',
        ),
    ]
