# Generated by Django 5.2.5 on 2025-10-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_rename_stepgroup_stepsynchronization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basestep',
            old_name='swim_lane',
            new_name='swimlane',
        ),
        migrations.RenameField(
            model_name='processstep',
            old_name='swim_lanes_constraint',
            new_name='swimlanes_constraint',
        ),
        migrations.RenameField(
            model_name='swimlaneindex',
            old_name='swim_lane',
            new_name='swimlane',
        ),
    ]
