# Generated by Django 5.2.5 on 2025-10-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_rename_swim_lane_basestep_swimlane_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StepSynchronization',
            new_name='StepParallelization',
        ),
    ]
